"""
Base Strategy Abstract Class
All strategies must inherit from this and implement required methods
"""

from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Optional, Dict, List, Any
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime
from loguru import logger

from core.client import PolymarketClient
from risk.risk_manager import RiskManager, RiskAction
from risk.position_sizing import PositionSizer
from utils.helpers import generate_trade_id


class SignalType(Enum):
    """Trading signal types"""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"


class SignalStrength(Enum):
    """Signal strength levels"""
    WEAK = 1
    MODERATE = 2
    STRONG = 3
    VERY_STRONG = 4


@dataclass
class TradingSignal:
    """Trading signal generated by strategy"""
    signal_type: SignalType
    token_id: str
    market_id: str
    price: Decimal
    estimated_prob: Decimal
    confidence: Decimal  # 0-1 confidence score
    reason: str
    strength: SignalStrength = SignalStrength.MODERATE
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)

    @property
    def edge(self) -> Decimal:
        """Calculate edge (difference between estimated prob and price)"""
        if self.signal_type == SignalType.BUY:
            return self.estimated_prob - self.price
        elif self.signal_type == SignalType.SELL:
            return self.price - self.estimated_prob
        return Decimal("0")

    def is_actionable(self, min_edge: Decimal = Decimal("0.03")) -> bool:
        """Check if signal has enough edge to act on"""
        return self.edge >= min_edge and self.signal_type != SignalType.HOLD

    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        return {
            "signal_type": self.signal_type.value,
            "token_id": self.token_id,
            "market_id": self.market_id,
            "price": str(self.price),
            "estimated_prob": str(self.estimated_prob),
            "confidence": str(self.confidence),
            "edge": str(self.edge),
            "reason": self.reason,
            "strength": self.strength.value,
            "timestamp": self.timestamp.isoformat()
        }


@dataclass
class Position:
    """Active position tracking"""
    trade_id: str
    market_id: str
    token_id: str
    side: str
    entry_price: Decimal
    size: Decimal
    entry_time: datetime
    current_price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def unrealized_pnl(self) -> Decimal:
        """Calculate unrealized PnL"""
        if self.current_price is None:
            return Decimal("0")

        if self.side.upper() == "BUY":
            return (self.current_price - self.entry_price) * self.size / self.entry_price
        else:
            return (self.entry_price - self.current_price) * self.size / self.entry_price

    @property
    def unrealized_pnl_pct(self) -> Decimal:
        """Calculate unrealized PnL as percentage"""
        if self.entry_price == 0 or self.size == 0:
            return Decimal("0")
        return (self.unrealized_pnl / self.size) * 100


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies

    Subclasses must implement:
    - analyze(): Analyze market and generate signals
    - execute(): Execute trades based on signals
    - get_name(): Return strategy name

    Provides:
    - Risk management integration
    - Position tracking
    - Logging and statistics

    Usage:
        class MyStrategy(BaseStrategy):
            def get_name(self) -> str:
                return "MyStrategy"

            async def analyze(self, market_data: Dict) -> Optional[TradingSignal]:
                # Analyze and generate signal
                pass

            async def execute(self, signal: TradingSignal) -> bool:
                # Execute trade
                pass
    """

    def __init__(
        self,
        client: PolymarketClient,
        risk_manager: RiskManager,
        position_sizer: PositionSizer
    ):
        """
        Initialize strategy

        Args:
            client: Polymarket API client
            risk_manager: Risk management instance
            position_sizer: Position sizing calculator
        """
        self.client = client
        self.risk_manager = risk_manager
        self.position_sizer = position_sizer
        self.active_positions: Dict[str, Position] = {}
        self.is_running = False

        # Statistics
        self.signals_generated = 0
        self.trades_executed = 0
        self.trades_won = 0
        self.trades_lost = 0

        logger.info(f"Strategy initialized: {self.get_name()}")

    @abstractmethod
    def get_name(self) -> str:
        """Return strategy name"""
        pass

    @abstractmethod
    async def analyze(self, market_data: Dict) -> Optional[TradingSignal]:
        """
        Analyze market data and generate trading signal

        Args:
            market_data: Market information including prices, order book, etc.

        Returns:
            TradingSignal if opportunity found, None otherwise
        """
        pass

    @abstractmethod
    async def execute(self, signal: TradingSignal) -> bool:
        """
        Execute trade based on signal

        Args:
            signal: Trading signal to execute

        Returns:
            True if execution successful
        """
        pass

    def can_trade(self) -> bool:
        """Check if trading is allowed by risk manager"""
        return self.risk_manager.can_open_new_position()

    def get_adjusted_size(self, base_size: Decimal) -> Decimal:
        """Get risk-adjusted position size"""
        multiplier = self.risk_manager.get_size_multiplier()
        return base_size * multiplier

    async def run_cycle(self, markets: List[Dict]) -> List[TradingSignal]:
        """
        Run one analysis/trading cycle

        Args:
            markets: List of markets to analyze

        Returns:
            List of signals generated (may or may not be executed)
        """
        signals = []

        for market in markets:
            try:
                signal = await self.analyze(market)

                if signal and signal.signal_type != SignalType.HOLD:
                    signals.append(signal)
                    self.signals_generated += 1

                    # Check if we should execute
                    if self.can_trade():
                        success = await self.execute(signal)
                        if success:
                            self.trades_executed += 1
                            logger.info(
                                f"[{self.get_name()}] Executed: "
                                f"{signal.signal_type.value} {signal.token_id}"
                            )
                    else:
                        logger.warning(
                            f"[{self.get_name()}] Signal skipped - trading restricted"
                        )

            except Exception as e:
                logger.error(
                    f"[{self.get_name()}] Error processing market "
                    f"{market.get('id', 'unknown')}: {e}"
                )

        return signals

    def add_position(
        self,
        market_id: str,
        token_id: str,
        side: str,
        entry_price: Decimal,
        size: Decimal,
        stop_loss: Decimal = None,
        take_profit: Decimal = None,
        metadata: Dict = None
    ) -> Position:
        """
        Add a new position to tracking

        Returns:
            Position object
        """
        trade_id = generate_trade_id()

        position = Position(
            trade_id=trade_id,
            market_id=market_id,
            token_id=token_id,
            side=side,
            entry_price=entry_price,
            size=size,
            entry_time=datetime.now(),
            stop_loss=stop_loss,
            take_profit=take_profit,
            metadata=metadata or {}
        )

        self.active_positions[market_id] = position

        # Register with risk manager
        self.risk_manager.register_open_position(
            trade_id=trade_id,
            market_id=market_id,
            side=side,
            entry_price=entry_price,
            size=size,
            strategy=self.get_name()
        )

        logger.info(
            f"[{self.get_name()}] Position opened: {side} ${size} @ {entry_price}"
        )
        return position

    def close_position(
        self,
        market_id: str,
        exit_price: Decimal
    ) -> Optional[Decimal]:
        """
        Close a position and record result

        Args:
            market_id: Market ID of position to close
            exit_price: Exit price

        Returns:
            PnL or None if position not found
        """
        position = self.active_positions.pop(market_id, None)

        if not position:
            logger.warning(f"Position not found for market: {market_id}")
            return None

        # Record with risk manager
        action = self.risk_manager.record_trade_result(
            trade_id=position.trade_id,
            market_id=market_id,
            side=position.side,
            entry_price=position.entry_price,
            exit_price=exit_price,
            size=position.size,
            strategy=self.get_name()
        )

        # Update position with exit price to calculate PnL
        position.current_price = exit_price
        pnl = position.unrealized_pnl

        # Update statistics
        if pnl >= 0:
            self.trades_won += 1
        else:
            self.trades_lost += 1

        logger.info(
            f"[{self.get_name()}] Position closed: PnL ${pnl:.2f}, "
            f"Risk action: {action.value}"
        )

        return pnl

    def update_position_price(self, market_id: str, current_price: Decimal):
        """Update current price for a position"""
        if market_id in self.active_positions:
            self.active_positions[market_id].current_price = current_price

    def check_stop_losses(self) -> List[str]:
        """
        Check all positions for stop-loss triggers

        Returns:
            List of market IDs that triggered stop-loss
        """
        triggered = []

        for market_id, position in self.active_positions.items():
            if position.current_price is None:
                continue

            if self.risk_manager.should_close_position(
                entry_price=position.entry_price,
                current_price=position.current_price,
                side=position.side,
                stop_loss_pct=None  # Use default
            ):
                triggered.append(market_id)
                logger.warning(
                    f"[{self.get_name()}] Stop-loss triggered for {market_id}"
                )

        return triggered

    def get_stats(self) -> Dict:
        """Get strategy statistics"""
        total = self.trades_won + self.trades_lost
        win_rate = self.trades_won / total if total > 0 else 0

        return {
            "name": self.get_name(),
            "signals_generated": self.signals_generated,
            "trades_executed": self.trades_executed,
            "trades_won": self.trades_won,
            "trades_lost": self.trades_lost,
            "win_rate": win_rate,
            "active_positions": len(self.active_positions),
            "is_running": self.is_running
        }

    def log_status(self):
        """Log current strategy status"""
        stats = self.get_stats()
        risk_status = self.risk_manager.check_risk_status()

        logger.info(
            f"\n[{self.get_name()}] Status:\n"
            f"  Active positions: {stats['active_positions']}\n"
            f"  Signals/Trades: {stats['signals_generated']}/{stats['trades_executed']}\n"
            f"  Win rate: {stats['win_rate']*100:.1f}%\n"
            f"  Daily PnL: ${risk_status.daily_pnl:.2f}\n"
            f"  Balance: ${risk_status.current_balance:.2f}\n"
            f"  Risk action: {risk_status.action.value}"
        )

    def start(self):
        """Start the strategy"""
        self.is_running = True
        logger.info(f"[{self.get_name()}] Strategy started")

    def stop(self):
        """Stop the strategy"""
        self.is_running = False
        logger.info(f"[{self.get_name()}] Strategy stopped")

    def reset_stats(self):
        """Reset strategy statistics"""
        self.signals_generated = 0
        self.trades_executed = 0
        self.trades_won = 0
        self.trades_lost = 0
        logger.info(f"[{self.get_name()}] Statistics reset")
